### ISSUE TITLE
Two accounts for trading

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#227]
Support two Accounts for trading within one strategy. This would allow taking both long/short positions simultaneously, taking advantage of hedging.

Currently only one account is used for trading, thus long and short position within the same time is not possible.

**Idea:**

Currently the signal within a strategy defintiion is governed by `signal` section in `stratvars` TOML followed by name of the signal - in the case below `main`. In the root section there are various attributtes (window open and close, stoplosses etc.) in `condition` section there are specific condition for LONG or SHORT positon. Account should probably be new attribute within root signal section.

```toml
[stratvars.signals.main_acc1]
    signal_only_on_confirmed = false
    next_signal_offset_from_last_exit = 15
    window_open = 7
    window_close = 360
    profit = 0.07
    account = "ACCOUNT1"
    account_type = "ALPACA-STOCKS" #optional account type (crypto in near future etc.)
[stratvars.signals.main_acc1.conditions]
    #preconditions 

    #SHORT ENTRY
    #signal.go_short_if_equals = -1
    signal_conf_short.go_short_if_equals = 1

[stratvars.signals.main_acc2]
    signal_only_on_confirmed = false
    next_signal_offset_from_last_exit = 15
    window_open = 7
    window_close = 360
    profit = 0.07
    account = "ACCOUNT2"
    account_type = "ALPACA-STOCKS" #optional account type (crypto in near future etc.)
[stratvars.signals.main_acc2.conditions]
    #preconditions 

    #SHORT ENTRY
    #signal.go_short_if_equals = -1
    signal_conf_short.go_short_if_equals = 1
```
TBD - more details usage, cross referencing etc.

**Impacted areas:**
1. Signal definition in `stratvars`
2. Trade Inventory
  - pendings
  - positions storage
  - position fetching
3. Trade managements
  - trade actions, trade/tradeUpdate entities (new attribute Account)
  - trade callabacks, including OrderUpdate thread (probably new thread+its lifecycle hooks)
  - storage of trades
4. Live Trading Interfaces 
  - self.interface.buy (account, side, size)
  - self.interface.pos(account)
5. Same for backtesting support and interface
6. Strategy Output
  - metrics (per account, joined) - equity curves, etc.
  - vizualizations (trades, metrics) on chart and chart details and/or reports
