### ISSUE TITLE
Max profit to quit - to support accounts

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#236]
Enable max profit to quit functionality (`StrategyClassicSL.py` - function `stop_when_max_profit_loss`) to be configured also on level of each account  (currently now only overall for all accounts).

Design a notation in stratvars, something along these lines:

```toml
max_rel_profit_to_quit = [0.8, 0.3]
max_rel_profit_to_quit = [ACCOUNT1, ACCOUNT2]
````
