### ISSUE TITLE
multiaccount closing mechanism - new directive in stratvars

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#239]
Implement closing position mechanism on the level of all account - meaning if there is potential profit from all open positions (for example pos on acc1 -200 pos on acc2 +400  (together +200) - if it is set to +200 - all positions will be closed.

It closes position if potential profit from all open trades reach this threshold.

in stratvars
```toml
close_trades_profit = 200 #abs value or relative value (come up with distinction)
accounts_for_close_trades = [ACCOUNT1, ACCOUNT2] #which accounts to include
```
