### ISSUE TITLE
Promyslet systémový design(pojmutí) tick based indikátoru s rolling časovým oknem

### ISSUE THREAD

**Issue by drew2323** [drew2323/v2trading#91]
Tak aby se daly dobře používat a vizualizovat, porovnávat a měly konzolidovaný timestamp - pro použití v ML.

Vymyslet.

Cílem je umožnit dynamické samplování marketu z ticků a ukládání do určité úrovně. A vymyslet jak tyto úrovně dávat do ML.

Nutnost je **grupovat indikátory se stejným timestampem.**

Nyní mám
- bary v rolzlišení baru.
- tick indikátory v rozlišení ticku

Už teď umožňují tick indikátory s rolling oknem (to je budoucnost) nicméně teď jsou ukládány do baru nebo ticku indikátorů. 

**Náčrt:**
Možná to grupovat podle časového okna?

Možná si udělat nějaký grupovací idenitifikátor.

Např. rw 7 - rolling window 7 a v tom by byly všechny tick indikátory s rolling window

cbar_indicators["TYP_GRUPOVANI"]["GRUPOVACI_HODNOTA]
Např.
cbar_indicators["rw"]["7"] ve kterém by byly všechny cbar_indikátory s oknem 7

- na gui by byly indikátory se stejným typem grupováním zobrazeny 
- Svoboda v samplování trhu na různých úrovních

Definování ve stratvars a přistpování v conditionech.

```toml
[stratvars.indicators.tick_tradecnt]
    output = 'tick'
    output_group_type = "rw" #sampling typu rolling window
    output_group_val = "7" # na 7mi vteřinách
    type = 'custom'
    subtype = 'barparams'
    on_confirmed_only = false
    cp.source = 'trades'
``` 

V cbar_indicators["rw"]["7"] pak budu mit vsechny indikatory se stejnym timestampem po 7mi vteřinách.

Domyslet Inicializace hodnote?
